FROM python:3.14.0a3-slim

RUN apt-get update && apt-get install -y libssl-dev libsqlite3-dev
WORKDIR /app
COPY . /app/
RUN pip install -r ./requirements.txt


# RUN pip install -r ./requirements.txt

EXPOSE 5000
# CMD ["flask","run", "--port=5000", "--host=0.0.0.0"]

CMD ["flask","run", "--port=5000", "--host=0.0.0.0", "--cert=/run/secrets/users_cert", "--key=/run/secrets/users_key"]