services:
  gateway_user:
    build: ./services/player_gateway
    ports:
      - 8080:443
    depends_on:
      - user_player
      - user_player_auth
    networks:
      - microservice-network
    volumes:
      - ./shared:/app/shared
    mem_limit: 256m
    secrets:
      - cert
      - key
      - novel
      - db_user
      - db_password

  gateway_admin:
    build: ./services/admin_gateway
    ports:
      - 8081:443
    depends_on:
      - user_admin
      - user_admin_auth
    networks:
      - microservice-network
    volumes:
      - ./shared:/app/shared
    mem_limit: 256m
    secrets:
      - cert
      - key
      - novel
      - db_user
      - db_password

  user_admin:
    build: ./services/admin
    depends_on:
      - users_db
    networks:
      - microservice-network
    volumes:
      - ./shared:/app/shared
    secrets:
      - cert
      - key
      - novel
      - db_user
      - db_password

  user_admin_auth:
    build: ./services/admin/auth
    depends_on:
      - users_db
    networks:
      - microservice-network
    volumes:
      - ./shared:/app/shared
    secrets:
      - cert
      - key
      - novel
      - db_user
      - db_password

  user_player:
    build: ./services/player
    depends_on:
      - users_db
    networks:
      - microservice-network
    volumes:
      - ./shared:/app/shared
    secrets:
      - cert
      - key
      - novel
      - db_user
      - db_password

  user_player_auth:
    build: ./services/player/auth
    depends_on:
      - users_db
    networks:
      - microservice-network
    volumes:
      - ./shared:/app/shared
    secrets:
      - cert
      - key
      - novel
      - db_user
      - db_password

  transaction:
    build: ./services/transaction
    depends_on:
      - transactions_db
    networks:
      - microservice-network
    volumes:
      - ./shared:/app/shared
    secrets:
      - cert
      - key
      - novel
      - db_user
      - db_password

  auction:
    build: ./services/auction
    depends_on:
      - auctions_db
    networks:
      - microservice-network
    volumes:
      - ./shared:/app/shared
    secrets:
      - cert
      - key
      - novel
      - db_user
      - db_password

  gacha:
    build: ./services/gacha
    depends_on:
      - gacha_db
    networks:
      - microservice-network
    volumes:
      - ./shared:/app/shared
    secrets:
      - cert
      - key
      - novel
      - db_user
      - db_password

  db-manager:
    build: ./services/dbm
    networks:
      - microservice-network
    depends_on:
      - users_db
    volumes:
      - ./shared:/app/shared
    secrets:
      - cert
      - key
      - novel
      - db_user
      - db_password


  auctions_db:
    build: db/auctions_db
    networks:
      - microservice-network
    volumes:
      - ./db/auctions_db/backup:/var/lib/auctions_db/backup:rw
    stop_signal: SIGTERM
    stop_grace_period: 30s
    mem_limit: 1024m
    secrets:
      - db_user
      - db_password


  transactions_db:
    build: db/transactions_db
    networks:
      - microservice-network
    volumes:
      - ./db/transactions_db/backup:/var/lib/transactions_db/backup:rw
    stop_signal: SIGTERM
    stop_grace_period: 30s
    mem_limit: 1024m
    secrets:
      - db_user
      - db_password

  users_db:
    build: db/users_db
    networks:
      - microservice-network
    volumes:
      - ./db/users_db/backup:/var/lib/users_db/backup:rw
    stop_signal: SIGTERM
    stop_grace_period: 30s
    mem_limit: 1024m
    secrets:
      - db_user
      - db_password

  gacha_db:
    build: db/gacha_db
    networks:
      - microservice-network
    volumes:
      - ./db/gacha_db/backup:/var/lib/gacha_db/backup:rw
    stop_signal: SIGTERM
    stop_grace_period: 30s
    mem_limit: 1024m
    secrets:
      - db_user
      - db_password

networks:
  microservice-network:
    driver: bridge

secrets:
  cert:
    file: ./cert.pem
  key:
    file: ./key.pem
  novel:
    file: ./poetry.txt
  db_user:
    file: ./db_user.txt
  db_password:
    file: ./db_password.txt
