services:
  gateway_user:
    build: ./services/player_gateway
    ports:
      - 8080:80
    depends_on:
      - db
      - user_admin
      - user_admin_auth
      - user_player
      - user_player_auth
    networks:
      - microservice-network

  gateway_admin:
    build: ./services/admin_gateway
    ports:
      - 8081:80
    depends_on:
      - db
      - user_admin
      - user_admin_auth
      - user_player
      - user_player_auth
    networks:
      - microservice-network
  # Importing the services
  user_admin:
    build: ./services/admin
    depends_on:
      - db-manager
    networks:
      - microservice-network

  user_admin_auth:
    build: ./services/admin/auth
    depends_on:
      - db-manager
    networks:
      - microservice-network

  user_player:
    build: ./services/player
    depends_on:
      - db-manager
    networks:
      - microservice-network

  user_player_auth:
    build: ./services/player/auth
    depends_on:
      - db-manager
    networks:
      - microservice-network
  
  transaction:
    build: ./services/transaction
    depends_on:
      - db-manager
    networks:
      - microservice-network
  
  auction:
    build: ./services/auction
    depends_on:
      - db-manager
    networks:
      - microservice-network
  
  gacha:
    build: ./services/gacha
    depends_on:
      - db-manager
    networks:
      - microservice-network
    volumes:
      - ./dbdata/gacha_db:/app/gacha.db

  
  db-manager:
    build: ./services/dbm
    depends_on:
      - db
    networks:
      - microservice-network
    volumes:
      - ./services/dbm/users_db:/app/user.db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    command: mongod --quiet --logpath /dev/null

volumes:
  dbdata:
  user_db_data:
  
networks:
  microservice-network:
    driver: bridge