services:
  gateway_user:
    build: ./services/player_gateway
    ports:
      - 8080:80
    networks:
      - microservice-network
    volumes:
      - ./shared:/app/shared

  gateway_admin:
    build: ./services/admin_gateway
    ports:
      - 8081:80
    networks:
      - microservice-network
    volumes:
      - ./shared:/app/shared

  user_admin:
    build: ./services/admin
    networks:
      - microservice-network
    volumes:
      - ./shared:/app/shared

  user_admin_auth:
    build: ./services/admin/auth
    networks:
      - microservice-network
    volumes:
      - ./shared:/app/shared

  user_player:
    build: ./services/player
    networks:
      - microservice-network
    volumes:
      - ./shared:/app/shared

  user_player_auth:
    build: ./services/player/auth
    networks:
      - microservice-network
    volumes:
      - ./shared:/app/shared

  transaction:
    build: ./services/transaction
    networks:
      - microservice-network
    volumes:
      - ./dbdata/transactions_db:/app/transactions.db
      - ./shared:/app/shared

  auction:
    build: ./services/auction
    networks:
      - microservice-network
    volumes:
      - ./dbdata/auctions_db:/app/auction.db
      - ./shared:/app/shared

  gacha:
    build: ./services/gacha
    networks:
      - microservice-network
    volumes:
      - ./dbdata/gacha_db:/app/gacha.db
      - ./shared:/app/shared

  db-manager:
    build: ./services/dbm
    networks:
      - microservice-network
    volumes:
      - ./dbdata/users_db:/app/users.db
      - ./shared:/app/shared

volumes:
  dbdata:
  user_db_data:


networks:
  microservice-network:
    driver: bridge


#add an environmental variable to the docker-compose.yml file to specify the debug mode or not

