FROM python:3.8-slim

RUN apt-get update && apt-get install -y libssl-dev libsqlite3-dev
WORKDIR /app
COPY . /app/
RUN pip install -r ./requirements.txt

# RUN apt-get update && apt-get install -y gcc && apt install libsqlite3-dev -y

# RUN pip install -r ./requirements.txt

EXPOSE 5000
# CMD ["flask","run", "--port=5000", "--host=0.0.0.0"]

CMD ["flask","run", "--port=5000", "--host=0.0.0.0", "--cert=/run/secrets/cert", "--key=/run/secrets/key"]
