FROM python:3.8-slim

WORKDIR /app
COPY . /app/
RUN pip install -r ./requirements.txt


# RUN pip install -r ./requirements.txt

EXPOSE 5000
# CMD ["flask","run", "--port=5000", "--host=0.0.0.0"]

CMD ["flask","run", "--port=5000", "--host=0.0.0.0", "--cert=/run/secrets/cert", "--key=/run/secrets/key"]