FROM python:3.12-slim

# upgrade openssl and sqlite3 to fix vulnerable version in image
RUN apt-get update && apt-get install -y libssl-dev libsqlite3-dev
WORKDIR /app
COPY . /app/
# RUN pip install -r requirements.txt

EXPOSE 5000
# CMD ["flask","run", "--port=5000", "--host=0.0.0.0"]

CMD ["/bin/bash","-c", "/app/shared/start.sh"]