name: CI Pipeline

on:
  push:
    branches:
      - ci-testing-postman
      - 'feature/*'
      # - 'feature/*' # Customize as needed

jobs:
  # Job 1: Unit Testing
  # unit_tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2

  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.x' # Define version based on requirements

  #     - name: Install dependencies
  #       run: |
  #         pip install -r requirements.txt

  #     - name: Run Unit Tests
  #       run: |
  #         pytest path/to/your/tests/unit_tests

  # Job 2: Build Microservice Architecture
  # Job 2: Build Microservice Architecture
  build_services:
    runs-on: ubuntu-latest
    container:
      image: docker/compose:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker containers
        run: docker-compose up --build -d

      - name: Stop Docker services
        if: always()
        run: docker-compose down

   # Job 3: Postman Tests
  postman_tests:
    runs-on: ubuntu-latest
    needs: build_services
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install newman
        run: npm install -g newman
      - name: Wait for services to be ready
        run: |
          while ! nc -z localhost 8080; do
            echo "Waiting for service on port 8080..."
            sleep 2
          done
          echo "Service is ready!"
      - name: Run Postman Tests
        run: |
          mkdir -p reports
          newman run postman_tests/GCTA_Tests.postman_collection.json -e postman_tests/gcta_env.postman_environment.json --reporters cli,html --reporter-html-export reports/newman-report.html
      - name: Upload Newman Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: reports/newman-report.html
      - name: Stop Docker services
        run: docker-compose down