name: CI Pipeline

on:
  push:
    branches:
      - ci-testing-postman

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start Docker services
        run: docker-compose up --build -d

      - name: Log running services and ports
        run: |
          echo "Listing running Docker services and their exposed ports:"
          docker ps

      - name: Wait for services to be ready
        run: |
          retries=30
          while ! nc -z localhost 8080; do
            echo "Waiting for service on port 8080..."
            sleep 10
            retries=$((retries - 1))
            if [ $retries -le 0 ]; then
              echo "Service did not start in time."
              exit 1
            fi
          done
          echo "Service is ready!"

        
      # - name: Check if containers can reach each other
      #   run: |
      #     retries=30
      #     while ! docker exec gcta_ase_2024-2025_gateway_user_1 curl -s http://127.0.0.1:8080; do
      #       echo "Waiting for containers to be able to reach each other..."
      #       sleep 10
      #       retries=$((retries - 1))
      #       if [ $retries -le 0 ]; then
      #         echo "Containers cannot reach each other."
      #         exit 1
      #       fi
      #     done
      #     echo "Containers can reach each other!"

      # - name: Check if localhost is accessible
      #   run: |
      #     retries=30
      #     while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 | grep -q 200; do
      #       echo "Waiting for localhost to be accessible..."
      #       sleep 5
      #       retries=$((retries - 1))
      #       if [ $retries -le 0 ]; then
      #         echo "Localhost is not accessible. Exiting."
      #         exit 1
      #       fi
      #     done
      #     echo "Localhost is accessible!"

      - name: Debug failing service
        run: |
          echo "Checking dbm logs:"
          docker logs gcta_ase_2024-2025-db-manager-1
           echo "Checking dbm logs version 2:"
          docker logs gcta_ase_2024-2025_db-manager_1

      - name: Install newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: |
          newman run postman_tests/GCTA_Tests.postman_collection.json -e postman_tests/gcta_env.postman_environment.json



      - name: Upload Newman Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: reports/newman-report.html

      - name: Stop Docker services
        if: always()
        run: docker-compose down
