name: Automated API tests using Postman CLI
on: push
jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key $PMAK-67409f1d2079a80001e8ff71-420e18e77fe7186ed41efd6a954a43564d
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/GCTA Tests.json"
