name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*' # Customize as needed

jobs:
  # Job 1: Unit Testing
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Define version based on requirements

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          pytest path/to/your/tests/unit_tests

  # Job 2: Build Microservice Architecture
  build_services:
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker containers
        run: |
          docker-compose up --build -d

  # Job 3: Integration Testing
  integration_tests:
    runs-on: ubuntu-latest
    needs: build_services
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Integration Tests
        run: |
          newman run path/to/your/postman_collection.json
